export const keys = {
  me: () => ['me'],
  dashboard: () => ['dashboard'],
  board: (f = {}) => ['board', f],
  tickets: (f = {}) => ['tickets', f],
  ticketsList: (f = {}) => ['tickets', 'list', f],
  ticket: (id) => ['tickets', String(id)],
  calendar: (f = {}) => ['calendar', f],
  tasks: (f = {}) => ['tasks', f],
  clients: (f = {}) => ['clients', f],
  client: (id) => ['clients', String(id)],
  projects: (f = {}) => ['projects', f],
  project: (id, f = {}) => ['projects', String(id), f],
  projectReports: (projectId) => ['projects', String(projectId), 'reports'],
  strategy: (projectId) => ['projects', String(projectId), 'strategy'],
  report: (id) => ['reports', String(id)],
  studio: () => ['studio'],
  creatives: (f = {}) => ['creatives', f],
  generations: (f = {}) => ['generations', f],
  socialAccounts: (clientId) => ['clients', String(clientId), 'social_accounts'],
  meetings: (f = {}) => ['meetings', f],
  invoices: (f = {}) => ['invoices', f],
  settings: () => ['settings'],
  billing: () => ['billing'],
  credits: () => ['credits'],
  creditUsage: (params = {}) => ['credits', 'usage', params],
  pricing: () => ['pricing'],
  workspaceMembers: () => ['workspace', 'memberships'],
  connections: () => ['connections'],
  mcpConnector: () => ['mcp_connector'],
  publicApproval: (token) => ['public', 'approvals', token],
  portal: (token) => ['public', 'portal', token],
  portalBoard: (token, projectId) => ['public', 'portal', token, 'campaigns', String(projectId), 'board'],
  portalMetrics: (token, projectId) => ['public', 'portal', token, 'campaigns', String(projectId), 'metrics'],
  portalReport: (token, projectId) => ['public', 'portal', token, 'campaigns', String(projectId), 'report'],
  posts: (f = {}) => ['posts', 'list', f],
  post: (id) => ['posts', String(id)],
  postsOverview: (f = {}) => ['posts', 'overview', f],
}
