export const keys = {
  me: () => ['me'],
  dashboard: () => ['dashboard'],
  board: (f = {}) => ['board', f],
  tickets: (f = {}) => ['tickets', f],
  ticketsList: (f = {}) => ['tickets', 'list', f],
  ticket: (id) => ['tickets', String(id)],
  calendar: (f = {}) => ['calendar', f],
  tasks: (f = {}) => ['tasks', f],
  clients: (f = {}) => ['clients', f],
  client: (id) => ['clients', String(id)],
  projects: (f = {}) => ['projects', f],
  project: (id, f = {}) => ['projects', String(id), f],
  studio: () => ['studio'],
  generations: (f = {}) => ['generations', f],
  socialAccounts: (clientId) => ['clients', String(clientId), 'social_accounts'],
  meetings: (f = {}) => ['meetings', f],
  invoices: (f = {}) => ['invoices', f],
  settings: () => ['settings'],
  billing: () => ['billing'],
  workspaceMembers: () => ['workspace', 'memberships'],
  connections: () => ['connections'],
  mcpConnector: () => ['mcp_connector'],
}
