# frozen_string_literal: true

module Operations
  module Social
    module Postgate
      # Requests a PostGate hosted-connect URL for one client + network. Ensures
      # the client has a PostGate ProfileGroup (1:1 with the client, created
      # lazily on first use and persisted onto `client.postgate_group_id`) before
      # asking PostGate for the connect URL, and builds the `return_url` PostGate
      # redirects the browser back to once the network authorizes (or fails) —
      # `Auth::PostgateController#return_from_connect`. `state` is generated by
      # the caller (the same signed_state helper the direct OAuth flow already
      # uses — verifier 'agencios:social_connect', payload
      # {'client_id','network','link'}) so
      # `Controllers::Auth::Postgate::ReturnFromConnect` can verify it the same way.
      class CreateConnectUrl < Operations::Base
        def initialize(client:, network:, state:, instance_url: nil, api_client: nil)
          @client = client
          @network = network.to_s
          @state = state
          @instance_url = instance_url
          @api_client = api_client || Vendors::Postgate::Client.new
        end

        def call
          response = @api_client.create_connect_url(
            platform: @network,
            profile_group_id: ensure_profile_group_id,
            return_url: return_url,
            instance_url: @instance_url
          )
          { url: response['url'] }
        end

        private

        # One ProfileGroup per client, created on first connect and reused after.
        def ensure_profile_group_id
          return @client.postgate_group_id if @client.postgate_group_id.present?

          group = @api_client.create_profile_group(name: @client.name, timezone: Time.zone.name)
          @client.update!(postgate_group_id: group['id'])
          @client.postgate_group_id
        end

        def return_url
          "#{SystemConfig.app_host}/auth/postgate/return?#{{ state: @state }.to_query}"
        end
      end
    end
  end
end
