# frozen_string_literal: true

# Estimated effort per subtask (hours). Generated by the strategy planner along
# with each task's back-scheduled due_date, and shown on the production checklist.
class AddEstimateHoursToSubtasks < ActiveRecord::Migration[8.1]
  def change
    add_column :subtasks, :estimate_hours, :decimal, precision: 5, scale: 2
  end
end
